"""
Master table of crits. Ammo, actuators, systems, weapons, etc.
"""

CRIT_TABLE = {
    'ShoulderOrHip': {},
    'UpperActuator': {},
    'LowerActuator': {},
    'HandOrFootActuator': {},
    'HeatSink': {},
    'LifeSupport': {},
    'Sensors': {},
    'Cockpit': {},
    'Engine': {},
    'Gyro': {},
    'FerroFibrous': {'add_special': 'FerroFibrous_Tech'},
    'LtFerroFibrous': {'add_special': 'LtFerroFibrous_Tech'},
    'HvyFerroFibrous': {'add_special': 'HvyFerroFibrous_Tech'},
    'EndoSteel': {'add_special': 'EndoSteel_Tech'},
    'StealthArmor': {'add_special': 'StealthArmor_Tech'},
    'NullSig_Device': {'add_special': 'NullSigSys_Tech'},
    'TripleStrengthMyomer': {'add_special': 'TripleMyomerTech'},
    'BeagleProbe': {'add_special': 'BeagleProbe'},
    'BloodhoundProbe': {'add_special': 'BloodhoundProbe_Tech'},
    'Masc': {'add_special': 'Masc'},
    'ArtemisIV': {'add_special': 'ArtemisIV'},
    'TargetingComputer': {'add_special': 'TargComp_Tech'},
    'Ecm': {'add_special': 'ECM'},
    'AngelEcm': {'add_special': 'AngelECM_Tech'},
    'CASE': {},
    'CASE-II': {},
    'JumpJet': {},
    'TAG': {},
    'C3Slave': {'add_special': 'C3SlaveTech'},
    'C3Master': {'add_special': 'C3MasterTech'},
    'C3i': {'add_special': 'C3I_Tech'},

    'Axe': {},
    'Claw': {},
    'Mace': {},
    'Sword': {},
}

WEAPON_TABLE = {
    'CL.A-Pod': {'crits': 1, 'ammo_count': 0},
    'CL.StreakSRM-2': {'crits': 1, 'ammo_count': 50},
    'CL.StreakSRM-4': {'crits': 1, 'ammo_count': 25},
    'CL.StreakSRM-6': {'crits': 2, 'ammo_count': 15},
    'IS.LongTom': {'crits': 30, 'ammo_count': 5},
    'PC.Blazer': {'crits': 1, 'ammo_count': 30},
    'PC.Crossbow': {'crits': 1, 'ammo_count': 20},
    'PC.FederatedLongRifle': {'crits': 1, 'ammo_count': 50},
    'PC.FlamerPistol': {'crits': 1, 'ammo_count': 50},
    'PC.GyroslugRifle': {'crits': 1, 'ammo_count': 15},
    'PC.HeavyGyrojetGun': {'crits': 1, 'ammo_count': 10},
    'PC.IntekLaserRifle': {'crits': 1, 'ammo_count': 45},
    'PC.LaserRifle': {'crits': 1, 'ammo_count': 30},
    'PC.PulseLaserPistol': {'crits': 1, 'ammo_count': 50},
    'PC.PulseLaserRifle': {'crits': 1, 'ammo_count': 30},
    'PC.SMG': {'crits': 1, 'ammo_count': 50},
    'PC.Shotgun': {'crits': 1, 'ammo_count': 10},
    'PC.SternsnachtPistol': {'crits': 1, 'ammo_count': 50},
    'PC.SunbeamLaserPistol': {'crits': 1, 'ammo_count': 50},
    'PC.ZeusHeavyRifle': {'crits': 1, 'ammo_count': 30},
    'IS.ELRM-5': {'crits': 1, 'ammo_count': 18},
    'IS.ELRM-10': {'crits': 4, 'ammo_count': 9},
    'IS.ELRM-15': {'crits': 6, 'ammo_count': 6},
    'IS.ELRM-20': {'crits': 8, 'ammo_count': 4},
    'IS.LR_DFM-5': {'crits': 1, 'ammo_count': 24},
    'IS.LR_DFM-10': {'crits': 2, 'ammo_count': 12},
    'IS.LR_DFM-15': {'crits': 3, 'ammo_count': 8},
    'IS.LR_DFM-20': {'crits': 5, 'ammo_count': 6},
    'IS.SR_DFM-2': {'crits': 1, 'ammo_count': 50},
    'IS.SR_DFM-4': {'crits': 1, 'ammo_count': 25},
    'IS.SR_DFM-6': {'crits': 2, 'ammo_count': 15},
    'IS.HyperAC/2': {'crits': 4, 'ammo_count': 30},
    'IS.HyperAC/5': {'crits': 5, 'ammo_count': 15},
    'IS.HyperAC/10': {'crits': 6, 'ammo_count': 8},
    'CL.ERLargeLaser': {'crits': 1, 'ammo_count': 0},
    'CL.ERMediumLaser': {'crits': 1, 'ammo_count': 0},
    'CL.ERSmallLaser': {'crits': 1, 'ammo_count': 0},
    'CL.ERMicroLaser': {'crits': 1, 'ammo_count': 0},
    'CL.ERPPC': {'crits': 2, 'ammo_count': 0},
    'CL.Flamer': {'crits': 1, 'ammo_count': 0},
    'CL.HeavyLargeLaser': {'crits': 3, 'ammo_count': 0},
    'CL.HeavyMediumLaser': {'crits': 2, 'ammo_count': 0},
    'CL.HeavySmallLaser': {'crits': 1, 'ammo_count': 0},
    'CL.LargePulseLaser': {'crits': 2, 'ammo_count': 0},
    'CL.MediumPulseLaser': {'crits': 1, 'ammo_count': 0},
    'CL.SmallPulseLaser': {'crits': 1, 'ammo_count': 0},
    'CL.MicroPulseLaser': {'crits': 1, 'ammo_count': 0},
    'CL.ERLargePulseLaser': {'crits': 3, 'ammo_count': 0},
    'CL.ERMediumPulseLaser': {'crits': 2, 'ammo_count': 0},
    'CL.ERSmallPulseLaser': {'crits': 1, 'ammo_count': 0},
    'CL.Anti-MissileSystem': {'crits': 1, 'ammo_count': 24, 'add_special': 'CL_AMS'},
    'CL.GaussRifle': {'crits': 6, 'ammo_count': 8},
    'CL.LB2-XAC': {'crits': 3, 'ammo_count': 45},
    'CL.LB5-XAC': {'crits': 4, 'ammo_count': 20},
    'CL.LB10-XAC': {'crits': 5, 'ammo_count': 10},
    'CL.LB20-XAC': {'crits': 9, 'ammo_count': 5},
    'CL.MachineGun': {'crits': 1, 'ammo_count': 200},
    'CL.LightMachineGun': {'crits': 1, 'ammo_count': 200},
    'CL.HeavyMachineGun': {'crits': 1, 'ammo_count': 100},
    'CL.UltraAC/2': {'crits': 2, 'ammo_count': 45},
    'CL.UltraAC/5': {'crits': 3, 'ammo_count': 20},
    'CL.UltraAC/10': {'crits': 4, 'ammo_count': 10},
    'CL.UltraAC/20': {'crits': 8, 'ammo_count': 5},
    'CL.ArrowIVSystem': {'crits': 12, 'ammo_count': 5},
    'CL.ATM-3': {'crits': 2, 'ammo_count': 20},
    'CL.ATM-6': {'crits': 3, 'ammo_count': 10},
    'CL.ATM-9': {'crits': 4, 'ammo_count': 7},
    'CL.ATM-12': {'crits': 5, 'ammo_count': 5},
    'CL.LRM-5': {'crits': 1, 'ammo_count': 24},
    'CL.LRM-10': {'crits': 1, 'ammo_count': 12},
    'CL.LRM-15': {'crits': 2, 'ammo_count': 8},
    'CL.LRM-20': {'crits': 4, 'ammo_count': 6},
    'CL.NarcBeacon': {'crits': 1, 'ammo_count': 6},
    'CL.SRM-2': {'crits': 1, 'ammo_count': 50},
    'CL.SRM-4': {'crits': 1, 'ammo_count': 25},
    'CL.SRM-6': {'crits': 1, 'ammo_count': 15},
    'IS.PPC': {'crits': 3, 'ammo_count': 0},
    'IS.LargeLaser': {'crits': 2, 'ammo_count': 0},
    'IS.MediumLaser': {'crits': 1, 'ammo_count': 0},
    'IS.SmallLaser': {'crits': 1, 'ammo_count': 0},
    'IS.Flamer': {'crits': 1, 'ammo_count': 0},
    'IS.ERPPC': {'crits': 3, 'ammo_count': 0},
    'IS.ERLargeLaser': {'crits': 2, 'ammo_count': 0},
    'IS.ERMediumLaser': {'crits': 1, 'ammo_count': 0},
    'IS.ERSmallLaser': {'crits': 1, 'ammo_count': 0},
    'IS.LargePulseLaser': {'crits': 2, 'ammo_count': 0},
    'IS.MediumPulseLaser': {'crits': 1, 'ammo_count': 0},
    'IS.SmallPulseLaser': {'crits': 1, 'ammo_count': 0},
    'IS.X-LargePulseLaser': {'crits': 2, 'ammo_count': 0},
    'IS.X-MediumPulseLaser': {'crits': 1, 'ammo_count': 0},
    'IS.X-SmallPulseLaser': {'crits': 1, 'ammo_count': 0},
    'IS.SnubNosedPPC': {'crits': 2, 'ammo_count': 0},
    'IS.LightPPC': {'crits': 2, 'ammo_count': 0},
    'IS.HeavyPPC': {'crits': 4, 'ammo_count': 0},
    'IS.AC/2': {'crits': 1, 'ammo_count': 45},
    'IS.AC/5': {'crits': 4, 'ammo_count': 20},
    'IS.AC/10': {'crits': 7, 'ammo_count': 10},
    'IS.AC/20': {'crits': 10, 'ammo_count': 5},
    'IS.VehicleFlamer': {'crits': 1, 'ammo_count': 20},
    'IS.MachineGun': {'crits': 1, 'ammo_count': 200},
    'IS.Anti-MissileSystem': {'crits': 1, 'ammo_count': 12, 'add_special': 'IS_AMS'},
    'IS.GaussRifle': {'crits': 7, 'ammo_count': 8},
    'IS.LightGaussRifle': {'crits': 5, 'ammo_count': 16},
    'IS.HeavyGaussRifle': {'crits': 11, 'ammo_count': 4},
    'IS.LB2-XAC': {'crits': 4, 'ammo_count': 45},
    'IS.LB5-XAC': {'crits': 5, 'ammo_count': 20},
    'IS.LB10-XAC': {'crits': 6, 'ammo_count': 10},
    'IS.LB20-XAC': {'crits': 11, 'ammo_count': 5},
    'IS.RotaryAC/2': {'crits': 3, 'ammo_count': 45},
    'IS.RotaryAC/5': {'crits': 6, 'ammo_count': 20},
    'IS.UltraAC/2': {'crits': 3, 'ammo_count': 45},
    'IS.UltraAC/5': {'crits': 5, 'ammo_count': 20},
    'IS.UltraAC/10': {'crits': 7, 'ammo_count': 10},
    'IS.UltraAC/20': {'crits': 10, 'ammo_count': 5},
    'IS.ArrowIVSystem': {'crits': 15, 'ammo_count': 5},
    'IS.Sniper': {'crits': 20, 'ammo_count': 10},
    'IS.Thumper': {'crits': 15, 'ammo_count': 20},
    'IS.HeavyFlamer': {'crits': 1, 'ammo_count': 10},
    'IS.LightAC/2': {'crits': 1, 'ammo_count': 45},
    'IS.LightAC/5': {'crits': 2, 'ammo_count': 20},
    'IS.LongTomCannon': {'crits': 15, 'ammo_count': 5},
    'IS.SniperCannon': {'crits': 10, 'ammo_count': 10},
    'IS.ThumperCannon': {'crits': 7, 'ammo_count': 20},
    'IS.HeavyMachineGun': {'crits': 1, 'ammo_count': 100},
    'IS.PlasmaRifle': {'crits': 2, 'ammo_count': 10},
    'IS.MML-3': {'crits': 2, 'ammo_count': 33},
    'IS.MML-5': {'crits': 3, 'ammo_count': 20},
    'IS.MML-7': {'crits': 4, 'ammo_count': 14},
    'IS.MML-9': {'crits': 5, 'ammo_count': 11},
    'IS.LRM-5': {'crits': 1, 'ammo_count': 24},
    'IS.LRM-10': {'crits': 2, 'ammo_count': 12},
    'IS.LRM-15': {'crits': 3, 'ammo_count': 8},
    'IS.LRM-20': {'crits': 5, 'ammo_count': 6},
    'IS.SRM-2': {'crits': 1, 'ammo_count': 50},
    'IS.SRM-4': {'crits': 1, 'ammo_count': 25},
    'IS.SRM-6': {'crits': 2, 'ammo_count': 15},
    'IS.MRM-10': {'crits': 2, 'ammo_count': 24},
    'IS.MRM-20': {'crits': 3, 'ammo_count': 12},
    'IS.MRM-30': {'crits': 5, 'ammo_count': 8},
    'IS.MRM-40': {'crits': 7, 'ammo_count': 6},
    'IS.NarcBeacon': {'crits': 2, 'ammo_count': 6},
    'IS.iNarcBeacon': {'crits': 3, 'ammo_count': 4},
    'IS.StreakSRM-2': {'crits': 1, 'ammo_count': 50},
    'IS.StreakSRM-4': {'crits': 1, 'ammo_count': 25},
    'IS.StreakSRM-6': {'crits': 2, 'ammo_count': 15},
    'IS.RL-10': {'crits': 1, 'ammo_count': 0},
    'IS.RL-15': {'crits': 2, 'ammo_count': 0},
    'IS.RL-20': {'crits': 3, 'ammo_count': 0},
    'IS.Thunderbolt-5': {'crits': 1, 'ammo_count': 12},
    'IS.Thunderbolt-10': {'crits': 2, 'ammo_count': 6},
    'IS.Thunderbolt-15': {'crits': 3, 'ammo_count': 4},
    'IS.Thunderbolt-20': {'crits': 5, 'ammo_count': 3},
    'PC.Sword': {'crits': 1, 'ammo_count': 0},
    'PC.Vibroblade': {'crits': 1, 'ammo_count': 0},
    'CL.StreakLRM-5': {'crits': 1, 'ammo_count': 24},
    'CL.StreakLRM-10': {'crits': 2, 'ammo_count': 12},
    'CL.StreakLRM-15': {'crits': 3, 'ammo_count': 8},
    'CL.StreakLRM-20': {'crits': 5, 'ammo_count': 6},
    'IS.A-Pod': {'crits': 1, 'ammo_count': 0},
    'IS.MagshotGaussRifle': {'crits': 2, 'ammo_count': 50},
    'IS.CoolantGun': {'crits': 1, 'ammo_count': 25},
    'IS.AcidThrower': {'crits': 2, 'ammo_count': 10},
    'IS.VehicleHeavyFlamer': {'crits': 1, 'ammo_count': 20},
    'CL.RotaryAC/2': {'crits': 4, 'ammo_count': 45},
    'CL.RotaryAC/5': {'crits': 5, 'ammo_count': 20},
    'CL.RotaryAC/10': {'crits': 7, 'ammo_count': 10},
    'CL.RotaryAC/20': {'crits': 10, 'ammo_count': 5},
    'CL.PlasmaRifle': {'crits': 2, 'ammo_count': 0},
    'CL.LaserAMS': {'crits': 1, 'ammo_count': 24},
    'IS.LaserAMS': {'crits': 1, 'ammo_count': 24},
    'IS.LightInfantryRifle': {'crits': 1, 'ammo_count': 20},
    'IS.InfantryRifle': {'crits': 1, 'ammo_count': 10},
    'IS.HeavyInfantryRifle': {'crits': 1, 'ammo_count': 5},
    'IS.InfantryMachineGun': {'crits': 1, 'ammo_count': 20},
    'IS.InfantryLaser': {'crits': 1, 'ammo_count': 0},
    'IS.InfantryFlamer': {'crits': 1, 'ammo_count': 0},
    'IS.InfantrySRM': {'crits': 1, 'ammo_count': 2},
    'IS.InfantryLRM': {'crits': 1, 'ammo_count': 1},
}


ITEM_TABLE = {}
ITEM_TABLE.update(CRIT_TABLE)
ITEM_TABLE.update(WEAPON_TABLE)
