
# Currently only contains a short form to full name mapping. The short name
# is only used bt bttechlist(), not in the template files.
TECH_TABLE = {
    'FUS': {'name': 'Fusion Engine'},
    'TSM': {'name': 'Triple Strenghth Myomer'},
    'CLAMS': {'name': 'Clan Anti-Missile System'},
    'ISAMS': {'name': 'Inner Sphere Anti-Missile System'},
    'DHS': {'name': 'Double Heatsinks'},
    'MASC': {'name': 'Myomer Accelerator Signal Circuitry'},
    'CLTECH': {'name': 'Clan Tech'},
    'FA': {'name': 'Flippable Arms'},
    'C3M': {'name': 'C3 Master'},
    'C3S': {'name': 'C3 Slave'},
    'AIV': {'name': 'Artemis IV Fire Control'},
    'ECM': {'name': 'Electronic Countermeasure Suite'},
    'BAP': {'name': 'Beagle Active Probe'},
    'SAL': {'name': 'Salvage-Towing Tech'},
    'CAR': {'name': 'Cargo Carrying Tech'},
    'SL': {'name': 'Search Light'},
    'LOAD': {'name': 'Loader Tech'},
    'AA': {'name': 'Anti Aircraft Sensor'},
    'NOSEN': {'name': 'No Sensors'},
    'SS': {'name': 'SS Ability'},
    'FF': {'name': 'Ferrofibrous Armor'},
    'ES': {'name': 'Endosteel Internals'},
    'XL': {'name': 'Extra-Light Fusion Engine'},
    'ICE': {'name': 'Internal Combustion Engine'},
    'LIFT': {'name': 'Lifter Tech'},
    'LENG': {'name': 'Light Fusion Engine'},
    'XXL': {'name': 'Extra-Extra Light Fusion Engine'},
    'CENG': {'name': 'Compact Fusion Engine'},
    'RINT': {'name': 'Reinforced Internals'},
    'CINT': {'name': 'Composite Internals'},
    'HARM': {'name': 'Hardened Armor'},
    'CP': {'name': 'Critproof Tech'},
    'STHA': {'name': 'Stealth Armor'},
    'HFF': {'name': 'Heavy Ferrofibrous Armor'},
    'LRARM': {'name': 'Laser Reflective Armor'},
    'REACTARM': {'name': 'Reactive Armor'},
    'NULL': {'name': 'Null Signature System'},
    'C3I': {'name': 'Improved C3 Computer'},
    'IJJ': {'name': 'Improved Jumpjets'},
    'MJJ': {'name': 'Mechanical Jumpjets'},
    'CHS': {'name': 'Compact Heatsinks'},
    'LHS': {'name': 'Laser Heatsinks'},
    'BLP': {'name': 'Bloodhound Active Probe'},
    'AECM': {'name': 'Angel ECM'},
    'WDOG': {'name': 'Watchdog Sensor Tech'},
    'LFF': {'name': 'Light Ferrofibrous Armor'},
    'TAG': {'name': 'Target Acquisition Gear'},
    'OMNI': {'name': 'Omni Tech'},
    'AV': {'name': 'Artemis V Fire Control'},
    'CAMO': {'name': 'Camoflauge Gear'},
    'INFC': {'name': 'Infantry Carrier'},
    'XLGYRO': {'name': 'Extra-Light Gyro'},
    'HDGYRO': {'name': 'Hardened Gyro'},
    'CGYRO': {'name': 'Compact Gyro'},
    'SWARM': {'name': 'Swarm Attack'},
    'MFRIEND': {'name': 'May Mount Friends'},
    'ALEG': {'name': 'Anti-Leg Attack'},
    'PSTEALTH': {'name': 'Purifier Stealth'},
    'KSTEALTH': {'name': 'Kage Stealth'},
    'ASTEALTH': {'name': 'Achileus Stealth'},
    'ISTEALTH': {'name': 'Infiltrator Stealth'},
    '2STEALTH': {'name': 'InfiltratorII Stealth'},
    'MJPACK': {'name': 'Must Jettison Pack'},
    'CJPACK': {'name': 'Can Jettison Pack'},
    'AXE': {'name': 'Axe Melee Weapon'},
    'MACE': {'name': 'Mace Melee Weapon'},
    'SWORD': {'name': 'Sword Melee Weapon'},
    'CASE': {'name': 'Cellular Ammunition Storage Equipment'},
    'VTOL': {'name': 'Vertical Take-off Ability'},
    'MTOW': {'name': 'Hand Actuators'},
    'CART': {'name': 'Carrier Tech'},
    'TCOMP': {'name': 'Targeting Computer'},
    'DUAL_SAW': {'name': 'Buzz Saw Melee Weapon'},
    'WPRF': {'name': 'Waterproof Sealing'},
    'SCHARGE': {'name': 'Supercharger'},
    'CASEII': {'name': 'Cellular Ammunition Storage Equipment II'},
    'SMCPIT': {'name': 'Small Cockpit'},
    'CLAW': {'name': 'Claw Melee Weapon'},
}
